# Generated by Django 4.1.3 on 2022-12-05 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=50)),
                ('age_range', models.CharField(choices=[('19_to_24', '19 - 24'), ('25_to_34', '25 - 34'), ('35_to_44', '35 - 44'), ('45_to_above', '45 & Above')], default='19_to_24', max_length=100)),
                ('annual_income', models.CharField(choices=[('below_1.5', 'Below 1.5 Million'), ('above_1.5', 'Above 1.5 Million'), ('above_2.5', 'Above 2.5 Million')], default='below_1.5', max_length=100)),
                ('intervals', models.IntegerField(default=1)),
                ('survey', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
